Repository pysal/libpysal, pull requests merged in 2018-07, with the labels that each got.

#61 [WIP]: add linestring/multilinestring functionality
  libpysal/weights/_contW_lists.py
Labels: scipy2018

#58 [WIP] Alpha shapes (2D) code
  .travis.yml
  libpysal/cg/__init__.py
  libpysal/cg/alpha_shapes.py
  libpysal/cg/tests/data/alpha_05.cpg
  libpysal/cg/tests/data/alpha_05.dbf
  libpysal/cg/tests/data/alpha_05.shp
  libpysal/cg/tests/data/alpha_05.shx
  libpysal/cg/tests/data/alpha_auto.cpg
  libpysal/cg/tests/data/alpha_auto.dbf
  libpysal/cg/tests/data/alpha_auto.shp
  libpysal/cg/tests/data/alpha_auto.shx
  libpysal/cg/tests/data/alpha_fifth.cpg
  libpysal/cg/tests/data/alpha_fifth.dbf
  libpysal/cg/tests/data/alpha_fifth.shp
  libpysal/cg/tests/data/alpha_fifth.shx
  libpysal/cg/tests/data/alpha_fourth.cpg
  libpysal/cg/tests/data/alpha_fourth.dbf
  libpysal/cg/tests/data/alpha_fourth.shp
  libpysal/cg/tests/data/alpha_fourth.shx
  libpysal/cg/tests/data/alpha_tenth.cpg
  libpysal/cg/tests/data/alpha_tenth.dbf
  libpysal/cg/tests/data/alpha_tenth.shp
  libpysal/cg/tests/data/alpha_tenth.shx
  libpysal/cg/tests/test_ashapes.py
  requirements_dev.txt
Labels: enhancement, scipy2018

#76 changed geometry column name from a str to an attribute
  libpysal/weights/util.py
Labels: bug, enhancement
