Repository pysal/libpysal, pull requests merged in 2019-05, with the labels that each got.

#154 bump supported Python versions and correct lat2SW doctest
  .travis.yml
  libpysal/weights/util.py
Labels: bug, maintenance

#156 BUG: fix for scipy bump #154
  libpysal/weights/util.py
Labels: bug, docs, maintenance

#122 update interactive examples in inline docstrings
  libpysal/weights/contiguity.py
  libpysal/weights/distance.py
  libpysal/weights/set_operations.py
  libpysal/weights/spatial_lag.py
  libpysal/weights/spintW.py
  libpysal/weights/user.py
  libpysal/weights/util.py
  libpysal/weights/weights.py
Labels: maintenance

#157 MAINT: bumping version for a release
  libpysal/__init__.py
Labels: maintenance
