Repository pysal/libpysal, pull requests merged in 2019-10, with the labels that each got.

#186 Cast arrays as lists (Issue 185)
  libpysal/weights/spintW.py
  libpysal/weights/weights.py
Labels: rough edge

#190 BUG: alpha_shape_auto can fail to contain all points in the set.
  libpysal/cg/alpha_shapes.py
  libpysal/cg/tests/data/alpha_auto.dbf
  libpysal/cg/tests/data/alpha_auto.shp
  libpysal/cg/tests/data/alpha_auto.shx
  libpysal/cg/tests/test_ashapes.py
Labels: bug

#192 removing iteritems decorator
  libpysal/common.py
Labels: maintenance

#193 [WIP] removing unused relics
  README.txt
  distribute_setup.py
Labels: WIP, maintenance

#129 decorating functions with requires()
  .travis.yml
  libpysal/cg/alpha_shapes.py
Labels: enhancement, rough edge

#196 Remove more relics (from pre-reorg PySAL)
  INSTALL.txt
  MANIFEST.in
  tools/ExtractFuncs_Docs.ipynb
  tools/cron.py
  tools/docs.sh
  tools/py3tool.py
  tools/spregsync
  tools/test.sh
Labels: maintenance

#200 fix quasi-redundant import of shapely
  libpysal/cg/alpha_shapes.py
Labels: rough edge

#201 [ENH] moving jit import to common.py / improve documentation
  libpysal/cg/alpha_shapes.py
  libpysal/common.py
Labels: enhancement, maintenance

#202 improved docs in io.util.shapefile
  libpysal/io/util/shapefile.py
Labels: docs, maintenance

#203 updating cg.standalone.distance_matrix docs
  libpysal/cg/standalone.py
Labels: docs, maintenance, rough edge
