Repository pysal/libpysal, pull requests merged in 2019-07, with the labels that each got.

#162 removing alumni devs from travis notifications (#161)
  .travis.yml
Labels: maintenance

#167 Modernize the travis builds
  .travis.yml
  CHANGELOG.md
  ci/travis/36-latest-conda-forge.yaml
  ci/travis/37-latest-conda-forge.yaml
Labels: maintenance

#171 minor change to W's silence_warnings workflow
  libpysal/weights/weights.py
Labels: enhancement, maintenance

#172 Ci
  .travis.yml
Labels: bug
