Repository pysal/libpysal, pull requests merged in 2020-02, with the labels that each got.

#237 BUG: ufunc.outer deprecated
  libpysal/weights/tests/test_adjlist.py
  libpysal/weights/tests/test_util.py
Labels: bug, examples

#239 correct name for beautifulsoup4
  requirements.txt
Labels: rough edge

#247 Appveyor
  .travis.yml
  appveyor.yml
  ci/travis/36-latest-conda-forge.yaml
  ci/travis/37-latest-conda-forge.yaml
  libpysal/io/iohandlers/tests/test_pyDbfIO.py
Labels: enhancement, tests

#243 DOC: Fix invalid section headings.
  libpysal/cg/sphere.py
Labels: docs, rough edge

#251 3.8
  .travis.yml
  appveyor.yml
  ci/travis/38-latest-conda-forge.yaml
  libpysal/cg/rtree.py
Labels: maintenance, tests

#250 Update reqs for tests
  .coveragerc
  .travis.yml
  README.rst
  requirements_tests.txt
  setup.py
Labels: maintenance, tests
