Repository pysal/libpysal, pull requests merged in 2022-11, with the labels that each got.

#482 test against shapely prerelease
  .github/workflows/unittests.yml
  ci/310_shapely_dev.yaml
Labels: maintenance, requirements, dependencies

#486 ENH: more granularity in example handling
  examples.ipynb
  libpysal/examples/__init__.py
  libpysal/examples/base.py
  libpysal/examples/builtin.py
  libpysal/examples/remotes.py
  libpysal/examples/tests/test_available.py
  notebooks/examples.ipynb
Labels: examples

#488 type vs. geom_type with shapely
  .pre-commit-config.yaml
  libpysal/examples/tests/test_available.py
  libpysal/weights/_contW_lists.py
Labels: maintenance, ci
