Repository pysal/libpysal, pull requests merged in 2023-10, with the labels that each got.

#580 Update release action, etc. to prep for v4.8.0
  .github/workflows/build_docs.yml
  .github/workflows/release_and_publish.yml
  .pre-commit-config.yaml
  docs/conf.py
  docs/installation.rst
  docs/tutorial.rst
Labels: docs, github_actions

#581 README is rst, not md --> update pyproject.toml
  pyproject.toml
Labels: docs, github_actions

#584 manual trigger for CI
  .github/workflows/unittests.yml
Labels: ci

#585 CI against Python 3.12
  .github/workflows/build_docs.yml
  .github/workflows/release_and_publish.yml
  .github/workflows/unittests.yml
  .pre-commit-config.yaml
  README.rst
  ci/310-oldest.yaml
  ci/310.yaml
  ci/312-dev.yaml
  ci/312-no-optional.yaml
  ci/312.yaml
  ci/39.yaml
  docs/conf.py
  docs/index.rst
  environment.yml
  pyproject.toml
Labels: maintenance, ci

#591 MAINT: avoid most of the warnings coming from dev CI
  libpysal/cg/alpha_shapes.py
  libpysal/cg/tests/test_ashapes.py
  libpysal/graph/_utils.py
  libpysal/graph/base.py
  libpysal/io/iohandlers/pyDbfIO.py
  libpysal/io/iohandlers/tests/test_gwt.py
  libpysal/weights/tests/test_util.py
  libpysal/weights/util.py
  pyproject.toml
Labels: rough edge, tests

#592 MAINT: dealing with `sqlalchemy` & `geomet`
  ci/310-oldest.yaml
  ci/310.yaml
  ci/311.yaml
  ci/312-dev.yaml
  ci/312.yaml
  libpysal/io/iohandlers/__init__.py
  libpysal/io/iohandlers/db.py
  libpysal/io/iohandlers/tests/test_db.py
  libpysal/weights/tests/test_user.py
  pyproject.toml
Labels: maintenance, dependencies

#598 convert README to markdown
  README.md
  README.rst
  pyproject.toml
Labels: maintenance

#597 begin the repo linting
  libpysal/cg/__init__.py
  libpysal/cg/ops/__init__.py
  libpysal/common.py
  libpysal/examples/__init__.py
  libpysal/io/__init__.py
  libpysal/io/iohandlers/__init__.py
  libpysal/io/util/__init__.py
  libpysal/weights/__init__.py
  pyproject.toml
Labels: maintenance

#600 remove `test_NameSpace.py`
  libpysal/test_NameSpace.py
Labels: maintenance

#601 TST: convert unittests to pytest
  libpysal/cg/ops/tests/test_accessors.py
  libpysal/cg/ops/tests/test_shapely.py
  libpysal/cg/ops/tests/test_tabular.py
  libpysal/cg/tests/test_ashapes.py
  libpysal/cg/tests/test_geoJSON.py
  libpysal/cg/tests/test_locators.py
  libpysal/cg/tests/test_polygonQuadTreeStructure.py
  libpysal/cg/tests/test_rtree.py
  libpysal/cg/tests/test_segmentLocator.py
  libpysal/cg/tests/test_shapes.py
  libpysal/cg/tests/test_sphere.py
  libpysal/cg/tests/test_standalone.py
  libpysal/cg/tests/test_voronoi.py
  libpysal/examples/tests/test_available.py
  libpysal/io/geotable/tests/test_utils.py
  libpysal/io/iohandlers/tests/test_arcgis_dbf.py
  libpysal/io/iohandlers/tests/test_arcgis_swm.py
  libpysal/io/iohandlers/tests/test_arcgis_txt.py
  libpysal/io/iohandlers/tests/test_csvWrapper.py
  libpysal/io/iohandlers/tests/test_dat.py
  libpysal/io/iohandlers/tests/test_db.py
  libpysal/io/iohandlers/tests/test_gal.py
  libpysal/io/iohandlers/tests/test_geobugs_txt.py
  libpysal/io/iohandlers/tests/test_geoda_txt.py
  libpysal/io/iohandlers/tests/test_gwt.py
  libpysal/io/iohandlers/tests/test_mat.py
  libpysal/io/iohandlers/tests/test_mtx.py
  libpysal/io/iohandlers/tests/test_pyDbfIO.py
  libpysal/io/iohandlers/tests/test_pyShpIO.py
  libpysal/io/iohandlers/tests/test_stata_txt.py
  libpysal/io/iohandlers/tests/test_wk1.py
  libpysal/io/iohandlers/tests/test_wkt.py
  libpysal/io/tests/test_FileIO.py
  libpysal/io/tests/test_Tables.py
  libpysal/io/util/tests/test_shapefile.py
  libpysal/io/util/tests/test_weight_converter.py
  libpysal/io/util/tests/test_wkt.py
  libpysal/weights/tests/test_Wsets.py
  libpysal/weights/tests/test__contW_lists.py
  libpysal/weights/tests/test_adjlist.py
  libpysal/weights/tests/test_contiguity.py
  libpysal/weights/tests/test_distance.py
  libpysal/weights/tests/test_gabriel.py
  libpysal/weights/tests/test_nx.py
  libpysal/weights/tests/test_raster.py
  libpysal/weights/tests/test_spatial_lag.py
  libpysal/weights/tests/test_spintW.py
  libpysal/weights/tests/test_user.py
  libpysal/weights/tests/test_util.py
  libpysal/weights/tests/test_weights.py
  libpysal/weights/tests/test_weights_IO.py
Labels: maintenance, tests

#604 remove redundant `.coveragerc`
  .coveragerc
  pyproject.toml
Labels: maintenance

#607 lint `./examples/*`
  libpysal/examples/base.py
  libpysal/examples/builtin.py
  libpysal/examples/remotes.py
  libpysal/examples/tests/test_available.py
Labels: maintenance

#608 `./cg/*.py` – format, lint, & remove docstring spaces
  libpysal/cg/alpha_shapes.py
  libpysal/cg/kdtree.py
  libpysal/cg/locators.py
  libpysal/cg/polygonQuadTreeStructure.py
  libpysal/cg/rtree.py
  libpysal/cg/segmentLocator.py
  libpysal/cg/shapely_ext.py
  libpysal/cg/shapes.py
  libpysal/cg/sphere.py
  libpysal/cg/standalone.py
  libpysal/cg/voronoi.py
Labels: maintenance

#610 format, lint, numpydoc – `cg/ops/*.py`
  libpysal/cg/ops/_accessors.py
  libpysal/cg/ops/_shapely.py
  libpysal/cg/ops/atomic.py
  libpysal/cg/ops/tabular.py
Labels: maintenance

#613 Print spatial versions in CI
  .github/workflows/unittests.yml
Labels: ci

#611 format & lint – `cg/ops/tests*.py`
  libpysal/cg/ops/tests/test_accessors.py
  libpysal/cg/ops/tests/test_shapely.py
  libpysal/cg/ops/tests/test_tabular.py
Labels: maintenance

#593 ENH: add vectorized plotting to Graph
  libpysal/graph/_plotting.py
  libpysal/graph/base.py
  libpysal/graph/tests/test_plotting.py
Labels: graph

#614 format & lint – `cg/tests/*.py`
  libpysal/cg/tests/test_ashapes.py
  libpysal/cg/tests/test_geoJSON.py
  libpysal/cg/tests/test_locators.py
  libpysal/cg/tests/test_rtree.py
  libpysal/cg/tests/test_segmentLocator.py
  libpysal/cg/tests/test_shapes.py
  libpysal/cg/tests/test_sphere.py
  libpysal/cg/tests/test_standalone.py
Labels: maintenance

#615 lint `graph/base.py`
  libpysal/graph/base.py
Labels: maintenance

#618 lint `graph/_*.py`
  libpysal/graph/_contiguity.py
  libpysal/graph/_kernel.py
  libpysal/graph/_parquet.py
  libpysal/graph/_plotting.py
  libpysal/graph/_set_ops.py
  libpysal/graph/_spatial_lag.py
  libpysal/graph/_triangulation.py
  libpysal/graph/_utils.py
  libpysal/graph/base.py
Labels: maintenance
