Repository pysal/libpysal, pull requests merged in 2023-11, with the labels that each got.

#619 lint & format `graph/tests/*.py`
  libpysal/graph/_utils.py
  libpysal/graph/tests/test_base.py
  libpysal/graph/tests/test_builders.py
  libpysal/graph/tests/test_contiguity.py
  libpysal/graph/tests/test_kernel.py
  libpysal/graph/tests/test_plotting.py
  libpysal/graph/tests/test_set_ops.py
  libpysal/graph/tests/test_spatial_lag.py
  libpysal/graph/tests/test_triangulation.py
  libpysal/graph/tests/test_utils.py
Labels: maintenance

#621 TST: ignore pandas dev blockmanager warnings
  pyproject.toml
Labels: tests

#620 lint & format `io/*.py`
  libpysal/io/fileio.py
  libpysal/io/tables.py
Labels: maintenance

#622 lint & format – `io/geotable/*`
  libpysal/io/geotable/dbf.py
  libpysal/io/geotable/file.py
  libpysal/io/geotable/shp.py
  libpysal/io/geotable/tests/test_utils.py
  libpysal/io/geotable/utils.py
  libpysal/io/geotable/wrappers.py
Labels: maintenance

#625 fix fileio regression
  libpysal/io/fileio.py
Labels: bug

#617 [WIP] explore method for graph
  libpysal/graph/_plotting.py
  libpysal/graph/base.py
  libpysal/graph/tests/test_plotting.py
  libpysal/graph/tests/test_utils.py
Labels: enhancement

#627 pass kwargs to explore
  libpysal/graph/_plotting.py
  libpysal/graph/base.py
  libpysal/graph/tests/test_plotting.py
Labels: rough edge, graph

#629 remove `xarray` as hard dependency
  ci/310-oldest.yaml
  ci/310.yaml
  ci/311.yaml
  ci/312-no-optional.yaml
  ci/312.yaml
  environment.yml
  libpysal/weights/tests/test_contiguity.py
  libpysal/weights/tests/test_raster.py
  pyproject.toml
Labels: maintenance, dependencies

#636 GHA: allow multi-core testing again
  .github/workflows/unittests.yml
Labels: ci

#637 lint & format `io/iohandlers{a-d}.py`
  libpysal/io/iohandlers/arcgis_dbf.py
  libpysal/io/iohandlers/arcgis_swm.py
  libpysal/io/iohandlers/arcgis_txt.py
  libpysal/io/iohandlers/csvWrapper.py
  libpysal/io/iohandlers/dat.py
  libpysal/io/iohandlers/db.py
Labels: maintenance

#638 lint & format `io/iohandlers{g-m}`.py
  libpysal/io/iohandlers/gal.py
  libpysal/io/iohandlers/geobugs_txt.py
  libpysal/io/iohandlers/geoda_txt.py
  libpysal/io/iohandlers/gwt.py
  libpysal/io/iohandlers/mat.py
  libpysal/io/iohandlers/mtx.py
Labels: maintenance

#641 lint & format `io/iohandlers{p-s}.py`
  libpysal/io/iohandlers/pyDbfIO.py
  libpysal/io/iohandlers/pyShpIO.py
  libpysal/io/iohandlers/stata_txt.py
Labels: maintenance

#642 lint & format `io/iohandlers{t-w}`.py
  libpysal/io/iohandlers/template.py
  libpysal/io/iohandlers/wk1.py
  libpysal/io/iohandlers/wkt.py
Labels: maintenance

#643 lint & format `io/iohandlers/tests/*.py`
  libpysal/io/iohandlers/tests/test_arcgis_dbf.py
  libpysal/io/iohandlers/tests/test_arcgis_swm.py
  libpysal/io/iohandlers/tests/test_arcgis_txt.py
  libpysal/io/iohandlers/tests/test_csvWrapper.py
  libpysal/io/iohandlers/tests/test_dat.py
  libpysal/io/iohandlers/tests/test_db.py
  libpysal/io/iohandlers/tests/test_gal.py
  libpysal/io/iohandlers/tests/test_geobugs_txt.py
  libpysal/io/iohandlers/tests/test_geoda_txt.py
  libpysal/io/iohandlers/tests/test_gwt.py
  libpysal/io/iohandlers/tests/test_mat.py
  libpysal/io/iohandlers/tests/test_mtx.py
  libpysal/io/iohandlers/tests/test_pyDbfIO.py
  libpysal/io/iohandlers/tests/test_pyShpIO.py
  libpysal/io/iohandlers/tests/test_stata_txt.py
  libpysal/io/iohandlers/tests/test_wk1.py
  libpysal/io/iohandlers/tests/test_wkt.py
Labels: maintenance

#644 lint & format `io/{tests, util}/*.py` part 1
  libpysal/io/tests/test_FileIO.py
  libpysal/io/tests/test_Tables.py
  libpysal/io/util/wkb.py
  libpysal/io/util/wkt.py
Labels: maintenance

#645 lint & format `io/{tests, util}/*.py` part 2
  libpysal/io/util/tests/test_shapefile.py
  libpysal/io/util/tests/test_weight_converter.py
  libpysal/io/util/tests/test_wkt.py
  libpysal/io/util/weight_converter.py
Labels: maintenance

#630 lint & format – `io/iohandlers/*`
  libpysal/graph/tests/test_utils.py
Labels: maintenance

#646 lint & format `io/{tests, util}/*.py` part 3
  libpysal/io/util/shapefile.py
Labels: maintenance

#648 lint & format `weights/*.py part 1
  libpysal/weights/_contW_lists.py
  libpysal/weights/adjtools.py
Labels: maintenance

#651 lint & format `weights/*.py part 3
  libpysal/weights/gabriel.py
  libpysal/weights/raster.py
  libpysal/weights/set_operations.py
Labels: maintenance

#652 lint & format `weights/*.py part 4
  libpysal/weights/spatial_lag.py
  libpysal/weights/spintW.py
  libpysal/weights/test.py
  libpysal/weights/user.py
Labels: maintenance

#653 lint & format `weights/*.py part 5
  libpysal/weights/util.py
Labels: maintenance

#654 lint & format `weights/*.py` part 6
  libpysal/weights/weights.py
Labels: maintenance

#655 lint & format weights/*.py part 7
  libpysal/weights/raster.py
  libpysal/weights/tests/test__contW_lists.py
  libpysal/weights/tests/test_adjlist.py
  libpysal/weights/tests/test_contiguity.py
  libpysal/weights/tests/test_distance.py
  libpysal/weights/tests/test_nx.py
  libpysal/weights/tests/test_raster.py
  libpysal/weights/tests/test_spatial_lag.py
  libpysal/weights/tests/test_spintW.py
  libpysal/weights/tests/test_weights_IO.py
Labels: maintenance

#658 lint & format `weights/*.py` part 8
  libpysal/weights/tests/test_Wsets.py
  libpysal/weights/tests/test_user.py
  libpysal/weights/tests/test_util.py
  libpysal/weights/tests/test_weights.py
  libpysal/weights/tests/test_weights_IO.py
  libpysal/weights/weights.py
Labels: maintenance

#640 ENH: add subgraph method to Graph to get subsets
  libpysal/graph/_utils.py
  libpysal/graph/base.py
  libpysal/graph/tests/test_base.py
Labels: enhancement, graph

#635 fast-path for initialisation of Graph for adjacency that is known to be sorted
  libpysal/graph/base.py
Labels: enhancement, graph

#634 ENH: Graph.eliminate_zeros, refactor isolates
  libpysal/graph/base.py
  libpysal/graph/tests/test_base.py
Labels: enhancement, graph

#659 revisit `cg/*.py` for missed lint & format
  libpysal/cg/kdtree.py
  libpysal/cg/locators.py
  libpysal/cg/polygonQuadTreeStructure.py
  libpysal/cg/segmentLocator.py
  libpysal/cg/shapes.py
  libpysal/cg/sphere.py
  libpysal/cg/standalone.py
  libpysal/cg/tests/test_geoJSON.py
  libpysal/cg/tests/test_polygonQuadTreeStructure.py
  libpysal/cg/tests/test_segmentLocator.py
  libpysal/cg/tests/test_standalone.py
Labels: maintenance

#660 correct in-line `ruff` syntax
  libpysal/cg/alpha_shapes.py
  libpysal/cg/locators.py
  libpysal/cg/ops/_accessors.py
  libpysal/cg/ops/_shapely.py
  libpysal/cg/ops/tabular.py
  libpysal/cg/ops/tests/test_shapely.py
  libpysal/cg/ops/tests/test_tabular.py
  libpysal/cg/rtree.py
  libpysal/cg/segmentLocator.py
  libpysal/cg/sphere.py
  libpysal/cg/standalone.py
  libpysal/cg/tests/test_sphere.py
  libpysal/cg/voronoi.py
  libpysal/common.py
  libpysal/examples/__init__.py
  libpysal/examples/base.py
  libpysal/examples/remotes.py
  libpysal/examples/tests/test_available.py
  libpysal/graph/_triangulation.py
  libpysal/graph/_utils.py
  libpysal/graph/base.py
  libpysal/graph/tests/test_set_ops.py
  libpysal/io/__init__.py
  libpysal/io/fileio.py
  libpysal/io/iohandlers/__init__.py
  libpysal/io/iohandlers/arcgis_dbf.py
  libpysal/io/iohandlers/arcgis_swm.py
  libpysal/io/iohandlers/arcgis_txt.py
  libpysal/io/iohandlers/csvWrapper.py
  libpysal/io/iohandlers/gal.py
  libpysal/io/iohandlers/geobugs_txt.py
  libpysal/io/iohandlers/gwt.py
  libpysal/io/iohandlers/mat.py
  libpysal/io/iohandlers/mtx.py
  libpysal/io/iohandlers/stata_txt.py
  libpysal/io/iohandlers/wk1.py
  libpysal/io/iohandlers/wkt.py
  libpysal/io/tables.py
  libpysal/io/util/shapefile.py
  libpysal/io/util/tests/test_shapefile.py
  libpysal/io/util/weight_converter.py
  libpysal/io/util/wkb.py
  libpysal/weights/__init__.py
  libpysal/weights/adjtools.py
  libpysal/weights/contiguity.py
  libpysal/weights/distance.py
  libpysal/weights/gabriel.py
  libpysal/weights/raster.py
  libpysal/weights/set_operations.py
  libpysal/weights/spatial_lag.py
  libpysal/weights/spintW.py
  libpysal/weights/tests/test__contW_lists.py
  libpysal/weights/tests/test_adjlist.py
  libpysal/weights/user.py
  libpysal/weights/util.py
  libpysal/weights/weights.py
Labels: maintenance

#661 final lint/format run through & update pre-commit
  .pre-commit-config.yaml
  libpysal/cg/standalone.py
  libpysal/graph/_kernel.py
  libpysal/io/fileio.py
  pyproject.toml
Labels: maintenance
