Repository pysal/libpysal, pull requests merged in 2024-01, with the labels that each got.

#673 TST: avoid using GeoDa Columbus from geodatasets
  .github/workflows/unittests.yml
  libpysal/graph/tests/test_utils.py
Labels: bug

#676 ENH: add Graph.apply, Graph.aggregate and allow callable as transformation in transform
  libpysal/graph/base.py
  libpysal/graph/tests/test_base.py
Labels: enhancement, graph

#639 GHA: include reverse dependency testing
  .github/workflows/reverse.yml
Labels: downstream

#666 Matching
  ci/310-oldest.yaml
  ci/310.yaml
  ci/311.yaml
  ci/312-dev.yaml
  ci/312-no-optional.yaml
  ci/312.yaml
  environment.yml
  libpysal/graph/_matching.py
  libpysal/graph/base.py
  libpysal/graph/tests/test_builders.py
  libpysal/graph/tests/test_matching.py
  notebooks/matching-graph.ipynb
  pyproject.toml
Labels: enhancement, needs review, graph

#680 DOC: include docstring in matching
  libpysal/graph/_matching.py
  libpysal/graph/base.py
Labels: docs

#679 update chat links: gitter >> discord
  README.md
  docs/index.rst
Labels: docs

#682 CI: partially resolve reverse dep testing issues
  .github/workflows/reverse.yml
Labels: maintenance, downstream
